### ISSUE TITLE
when `apply_nonlin=None` calculation of GDiceLoss fails because softmax_output is not created

### ISSUE THREAD

**Issue by neuronflow** [JunMa11/SegLoss#11]
when `apply_nonlin=None` calculation of GDiceLoss fails:
```
Traceback (most recent call last):
  File "path/loser.py", line 181, in <module>
    loss = criterion(prediction, label)
  File "path/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "path/SegLoss/losses_pytorch/dice_loss.py", line 123, in forward
    intersection: torch.Tensor = w * einsum("bcxyz, bcxyz->bc", softmax_output, y_onehot)
UnboundLocalError: local variable 'softmax_output' referenced before assignment
```

**Comment by neuronflow** [comment]
the same problem exists for:
`GDiceLossV2`

my tensors already have a non linearity applied so there is no reason to do it again :)

**Comment by JunMa11** [comment]
Hi @neuronflow ,

Thanks for pointing out this issue.

However, I'm currently busy with my thesis.
I will try to fix it after submitting my thesis.

Before that, please try this [one](https://github.com/LIVIAETS/surface-loss/blob/cd993c89dacc203bdab45cb20cf278d932ccd619/losses.py#L29).

Sorry for the inconvenience.

Best,
Jun

**Comment by clementpoiret** [comment]
I just pushed a quick PR to fix this issue :) 
https://github.com/JunMa11/SegLoss/pull/15

I hope it'll help
