### ISSUE TITLE
Where is the code for DiceFocal loss?

### ISSUE THREAD

**Issue by aviadpinis** [JunMa11/SegLoss#16]
Hello, it's amazing repository thank you for share your code,

I have two questions:

I try to use in DiceTopK loss function and i not sure that I understood that parameters to use correctly in this loss function,
what is meaning in this paramaters:
 * batch_dice,
 * do_bg.

I would be very happy if you could explain them to me?

Also i search in your code for implementation for DiceFocal and i I can not find, Can you please direct me to link?

Thank you very much,
Aviad

**Comment by JunMa11** [comment]
Hi @aviadpinis ,

Sorry for my late reply.

- batch_dice: treats the minibatch as a pseudo-volume and computes the Dice loss as if all voxels in the samples belonged to one training case.

A counterpart is 
- sample_dice: computes the dice loss for each sample in the minibatch independently and averages across the minibatch

- do_bg: whether compute the background loss;


`DiceFocal` is the simple summation between Dice loss and Focal loss.

https://github.com/JunMa11/SegLoss/blob/bea91a4e72c78fe63335fe9333d6659489ceb1b4/test/loss_functions/dice_loss.py#L499

**Comment by aviadpinis** [comment]
Thank you,
you helped me a lot
