### ISSUE TITLE
Focal Loss

### ISSUE THREAD

**Issue by ruiruian** [JunMa11/SegLoss#18]
Hello， @JunMa11 

I want to know whether focal loss is suitable for 3D image segmentation or not，and for segmentation with only two classifications of background and foreground，whether the network can be single-channel output and use focal loss.

Hope your help, thank you!

**Comment by JunMa11** [comment]
Hi @ruiruian 

> whether focal loss is suitable for 3D image segmentation or not，

Yes, It can be used in 3D segmentation tasks.
 Now, it is designed for two-class and multi-class segmentation.

**Comment by ruiruian** [comment]
Thank you @JunMa11 

I have a question, for two-class segmentation, whether the network can be single-channel output.

**Comment by JunMa11** [comment]
Hi @ruiruian ,

Sorry for my late reply.
Not yet. You should use to two-channel output with the current code.
