### ISSUE TITLE
'--ndet' flag

### ISSUE THREAD

**Issue by abergsneider** [JunMa11/SegLoss#19]
Hi Jun,

Thank you so much for sharing this with everyone. I'm coming from the nnU-Net repository after researching some of the issues posted.

I'm getting ready to implement your repository but noticed the `--ndet` flag at the end of the suggested run command `python run/run_training.py 3d_fullres nnUNetTrainer_Dice TaskXX_MY_DATASET FOLD --ndet`. I'm not familiar with what this flag does, and I can't seem to find any information about it anywhere. My best guess is that it is for **non-deterministic training** but I think nnU-Net does this by default.

Any info is much appreciated. Take care!

Andres

**Comment by JunMa11** [comment]
Hi @abergsneider ,

Thanks for your interest very much.

I guess you are using the nnU-Net V2. However, my repo was developed with nnU-Net V1.

If you want to use the `Dice` loss to train your model, I would recommend [nnUNetTrainerV2_Loss_Dice.py](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/training/network_training/nnUNet_variants/loss_function/nnUNetTrainerV2_Loss_Dice.py).

```
nnUNet_train 3d_lowres nnUNetTrainerV2_Loss_Dice TaskXXX_MYTASK FOLD
```

Hope this answer can help you.  Also, please feel free to raise any questions.


Best regards,
Jun

**Comment by abergsneider** [comment]
Thanks @JunMa11, I will go ahead and play around with those loss functions. And thanks for kindly pointing me in the right direction.

Best,

Andres
