### ISSUE TITLE
About nnunet 

### ISSUE THREAD

**Issue by Eurus-Holmes** [JunMa11/SegLoss#2]
Hi, thanks for your works!
In your codes, they all need `from nnunet.xxx`, should I install `nnunet` from https://github.com/MIC-DKFZ/nnUNet?
Why not provide individual loss function and test example codes?

**Comment by JunMa11** [comment]
Hi @Eurus-Holmes,

Sorry for my late reply.
I tested all  the losses based on `nnunet` and some codes were copy from `nnunet`. 
I will provide an individual folder to make the losses self-contained after my vacation. They will be released before 02/09/2019.

Best,
Jun

**Comment by JunMa11** [comment]
Hi @Eurus-Holmes,

I provide an individual folder `losses_pytorch` that contains plug-and-play loss functions.

Best,
Jun

**Comment by Eurus-Holmes** [comment]
@JunMa11 Thanks for your works!
