### ISSUE TITLE
IoULoss

### ISSUE THREAD

**Issue by kirmanserdar** [JunMa11/SegLoss#22]
Hi jun,

I want to ask that in [IoULoss](https://github.com/JunMa11/SegLoss/blob/master/losses_pytorch/dice_loss.py) ` def forward(self, x, y, loss_mask=None):` How your output can be minus if it is not minus why did you use `return -iou`

thanks

**Comment by JunMa11** [comment]
Hi @kirmans ，

the  iou loss is `1-iou`.  However, the constant `1` has no contribution to gradient during back-propagation because its derivative is 0.
Thu, `1` can be omitted.


Best,
Jun
