### ISSUE TITLE
Boundary Loss for Multi Class

### ISSUE THREAD

**Issue by daandres** [JunMa11/SegLoss#23]
The boundary loss and the sample for computing the distance map (input to boundary loss) both mentioned, that there are for binary masks. 

How would I use the Boundary loss in a multi class scenario?
How would I compute the sdf map for multi class?

Thank you!

**Comment by JunMa11** [comment]
Hi @daandres ,

The boundary loss  can be used to multi-class tasks.
https://github.com/JunMa11/SegLoss/blob/71b14900e91ea9405d9705c95b451fc819f24c70/test/loss_functions/boundary_loss.py#L131

Following is the implementation of sdf for multi class
https://github.com/JunMa11/SegLoss/blob/71b14900e91ea9405d9705c95b451fc819f24c70/test/loss_functions/boundary_loss.py#L102


I also notice that the official repo of boundary loss has supported the multi-class setting.
https://github.com/LIVIAETS/boundary-loss


Hope the answer can help you.


Best,
Jun

**Comment by daandres** [comment]
ok thanks. 
I noticed the original repo and just use its implementation.
