### ISSUE TITLE
Data preprocessing

### ISSUE THREAD

**Issue by xifang001** [JunMa11/SegLoss#27]
Hi, @JunMa11,

Thanks for your great work. I have a question about data preprocessing. As you've provided the detailed splits for the datasets. Could you further provide the code for liver CT dataset processing, so we can compare our results with yours directly?

Best,
Xi

**Comment by JunMa11** [comment]
Hi @xifang001 ,

We use the default data preprocessing in nnU-Net.

for nnU-Net V1 Resuls, run
```
python experiment_planning/plan_and_preprocess_task.py -t TaskXX_MY_DATASET -pl Y -pf Z
```

Currently, we are re-evaluating the popular plug-and-play losses with nnU-Net  V2. The preprocessing command is
```
nnUNet_plan_and_preprocess -t XXX 
```

Results are available here
https://github.com/JunMa11/SegLoss/tree/master/test

**Comment by xifang001** [comment]
Thanks for your reply. That sounds great. I'll try that one.

**Comment by JunMa11** [comment]
Hi @xifang001 ,
You can download the dataset here
https://pan.baidu.com/s/1reGPEiQico1SGaONMDSv8Q 
PW：2021

**Comment by xifang001** [comment]
Hi, @JunMa11, 
Pretty useful. Thanks so much!

**Comment by JunMa11** [comment]
Happy to help:)
