### ISSUE TITLE
Please add a license to this repository

### ISSUE THREAD

**Issue by proxyma-centauri** [JunMa11/SegLoss#34]
Hello,

First of all, thanks for your repository! I would like to use some of the loss functions that are in it in my project, and this is why I'm opening this issue to ask you to add a license to your repository.

As explained in [GitHub's help site on license choosing](https://choosealicense.com/no-permission/), not providing a license for your repository means that _"the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation."_ 

As per the way the README of this repository is written, I'm assuming that the lack of license is more of an oversight than a wish to restrict the use of this repository ; though if I'm wrong, and you actually do not want to add a license to your repository, could you state so in the README ?

Thank you for your time, and the consideration of this request !

**Comment by JunMa11** [comment]
Hi @proxyma-centauri ,

I have added Apache License 2.0.

Best,
Jun

**Comment by proxyma-centauri** [comment]
Many thanks!
