### ISSUE TITLE
About distance map

### ISSUE THREAD

**Issue by Holliemin9090** [JunMa11/SegLoss#37]
Hi JunMa,

Thanks alot for your code. 
I am just wondering as to boudary loss, should the distance map be a signed distance map (negative inside and positive outside the boundary) or an un-signed distance map (positive both inside and outside)?
Thanks in advance.

Cheers.

**Comment by JunMa11** [comment]
Hi,

You can find a clear answer in the original repo
https://github.com/LIVIAETS/boundary-loss
