### ISSUE TITLE
How long will it take to train with DICEHD on multiorgan dataset by nnunet?

### ISSUE THREAD

**Issue by Tunaaaaa** [JunMa11/SegLoss#39]
When train using nnunet with loss of DiceHD or DiceBD, it seems that in most of time the usage of GPU is around 0%,  few time is around 40%.  Looks like around 30 mins will cost for 1 epoch. Is this the normal situation?

I built my own dataset which is similar with _Multi-organ Abdominal CT_ and preprocess it according to the instruction of nnunet. Then I copied [https://github.com/JunMa11/SegLoss/blob/master/test/nnUNetV1/network_training/nnUNetTrainer_DiceBD.py](url)  and lossfunctions to nnunet folder. I replaced all _nnUNetTrainer_ to _nnUNetTrainerV2_ . Is this the right procedure?

Thank you very much!

**Comment by JunMa11** [comment]
Hi @Tunaaaaa ,

It's normal because both HD loss and BD loss need to compute the distance transform map that costs lots of CPU computations.

The right way to use the two losses is training with Dice loss and fine-tune with DiceHD/DiceBD loss. I would recommend looking at the original papers to get more insights:)

**Comment by Tunaaaaa** [comment]
> Hi @Tunaaaaa ,
> 
> It's normal because both HD loss and BD loss need to compute the distance transform map that costs lots of CPU computations.
> 
> The right way to use the two losses is training with Dice loss and fine-tune with DiceHD/DiceBD loss. I would recommend looking at the original papers to get more insights:)

Hi,

    Thank you~ At least I didn't get the code wrong, which is good news.  XD

Best
Junyu
