### ISSUE TITLE
Which one is the loss from "Topology-Preserving Deep Image Segmentation" paper ?

### ISSUE THREAD

**Issue by Optimox** [JunMa11/SegLoss#4]
Hi,

Thanks for this nice repo! I'm looking for the loss from this paper "Topology-Preserving Deep Image Segmentation" it seems to appear your table so I guess you've implemented it but I did not find it. Would you mind pointing me the correct loss function please?

Thank you very much,

Bests

**Comment by JunMa11** [comment]
Hi @Optimox 

Here is the official implementation.
https://github.com/HuXiaoling/TopoLoss

Best
Jun

**Comment by Optimox** [comment]
Thank you very much!

**Comment by Optimox** [comment]
@JunMa11 just to be sure, is there an implementation of your own about this loss on the repo?

**Comment by JunMa11** [comment]
Hi @Optimox ,

No.

Best,
Jun
