### ISSUE TITLE
About Sensitivity Specificity loss function implementation

### ISSUE THREAD

**Issue by Liqq1** [JunMa11/SegLoss#45]
Hello, I have a doubt about Sensitivity Specificity loss function's implementation.
<img width="538" alt="image" src="https://user-images.githubusercontent.com/54054113/179383776-0877b89e-d683-40a2-bca2-43cbd2deb66a.png">
So I think that the correct way to translate this Sensitivity into **prediction ** and **ground_truth ** terms for a loss function would be similar to:
true_positives = prediction*ground_truth
false_negatives = (1-prediction)*ground_truth
<img width="544" alt="image" src="https://user-images.githubusercontent.com/54054113/179383864-da51331f-1fb7-4739-81fa-2a0c1b88d288.png">
But in the implementation:
Sensitivity = (square(ground_truth-prediction) * (1-one_hot) ) / (1-one_hot)
How should I interpret its expressions(The same occurs with the Specificity )？

**Comment by JunMa11** [comment]
Hi, 

Please check their paper for the details

<img width="767" alt="image" src="https://github.com/JunMa11/SegLoss/assets/19947331/50e2ec77-c4e8-4327-9447-c48fae278677">
