### ISSUE TITLE
why is there no resolution input in the distance_map computing(scipy.ndimage.distance_transform_edt)?

### ISSUE THREAD

**Issue by SummerZ2020** [JunMa11/SegLoss#47]
Hello, 
   Thanks for sharing the code. it helps me a lot. The paper (loss odyssey ) is also great for me to know more about loss in medical segmentation. 
   I have found that in your code, the resolution is not considered in distance_map computing. However, it is used here[https://github.com/LIVIAETS/boundary-loss](url). 
   Why is the resolution  not be used here? Looking forward to your reply. Thanks a lot.

**Comment by JunMa11** [comment]
Thanks for your interest. 

We didn't use it because nnunet already resamples them into the same spacing during preprocessing.
