### ISSUE TITLE
instance segmentation loss

### ISSUE THREAD

**Issue by madurner** [JunMa11/SegLoss#5]
Hey! First of all, thanks for this really nice summary of all the different losses!!! That's amazing... Since you are kind of an expert with all these losses just one question: 
Which loss do you suggest for Instance Segmentation where the given dataset contains negative samples (i.e. no instance in the scene). In several works, these samples would be filtered and not used in the loss, however, in my current case, this is not possible. Dice loss? However, it is not capable of negative samples (since the GT-mask is empty there is no intersection no matter what is predicted).
Would be nice to read your opinion on that!

**Comment by JunMa11** [comment]
Dear @madurner ,

Sorry for my late reply.

Thanks for raising the great question.
However, I do not have any experience in instance segmentation. So I could not give you some useful suggestions.

Best,
Jun
