### ISSUE TITLE
paper link of Region Mutual Information Loss for Semantic Segmentation is wrong

### ISSUE THREAD

**Issue by ytliang97** [JunMa11/SegLoss#7]
Hi, thank you so much for collecting these papers.

I've noticed that the paper link of this paper is wrong, and it is link to another paper called "Correlation Maximized Structural Similarity Loss for Semantic Segmentation."

201910 | Shuai Zhao | Region Mutual Information Loss for Semantic Segmentation
-- | -- | --

**Comment by JunMa11** [comment]
Hi @ytliang97 ,

Thanks for pointing out this issue.

The problem is fixed.
